### PR TITLE
Build 19.8.0

### PR DESCRIPTION
**Pull request by rjurney**
Checklist
* [*] Used a fork of the feedstock to propose changes
* [*] Bumped the build number (if the version is unchanged)
* [*] Reset the build number to `0` (if the version changed)
* [*] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
```
@conda-forge-admin please rerender
```
* [*] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rjurney** [comment]
@kwilcox @daf @jakirkham @sodre it looks like everything passed. Is there anything more that I need to do?

**Comment by daf** [comment]
@rjurney you're downgrading from 19.9.0 to 19.8.0?

**Comment by rjurney** [comment]
@daf Superset uses 19.8.0, so yes. I need that version published on conda-forge to install its prerequisites with conda. If you accept the pull into a new 19.8.0 branch it should build and push it out without replacing the old one?

**Comment by ocefpaf** [comment]
@rjurney assuming you are not going to maintain the older version we can merge this and let be bot update it to the latest version again. However, if ou do want to maintain this older version you will need to send that to a branch.

**Pull request merged**
